version: '3'
services:
  app:
    env_file: .env
    build: .
    volumes:
      - .:/usr/src/app
    image: "mydadisalive/pizza-express:$VER"
    ports:
      - "$PORT:3000"
    links:
      - redis
    container_name: "${IMAGE}"
    environment:
      - REDIS_URL=redis://redis
      - NODE_ENV=development
      - PORT=3000
    command:
        sh -c 'npm i && npm install --save body-parser && node server.js'
  redis:
    image: "redis:alpine"
    container_name: redis
    expose:
      - 6379




